# Generated by Django 6.0.2 on 2026-02-11 06:44

import services.uploads
import services.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_branch_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploads.logo_upload_path, validators=[services.validations.image_validation]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploads.avatar_upload_path, validators=[services.validations.image_validation]),
        ),
    ]
